### ISSUE TITLE
Automate showing the latest month and the next months in the view

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/chefrank#1]
Currently, if you goto http://rhnvrm.github.io/chefrank/ you will see the rankings for JUNE 16 since it has been hardcoded. This should be fixed and automated to show the current month on the top

**Comment by mbad0la** [comment]
Hi! I'd love to help you out on this :)

**Comment by rhnvrm** [comment]
@mbad0la Sure, please do send a pull request :+1:

**Comment by mbad0la** [comment]
Will do tomorrow morning! Cheers.

**Comment by rhnvrm** [comment]
@mbad0la, @asmita005 already sent a MR for this. Thanks though! :+1:

**Comment by mbad0la** [comment]
@rhnvrm this is really disappointing. 
In open source we always have to maintain a degree of trust and fairness with our contributors. If someone claims an issue, you don't merge someone else's code fixing that issue.
This is just a suggestion, which is followed by heart at every good open source community and project.
